let firstNamesF = ["Brigitte","Renate","Karin","Angelika","Monika","Ursula","Ingrid","Marion","Barbara","Gisela","Helga","Jutta","Hannelore","Gabriele","Birgit","Christa","Marianne","Bärbel","Maria","Elke","Petra","Rita","Sigrid","Christine","Erika","Gudrun","Marlies","Ute","Christel","Regina","Christiane","Ruth","Sabine","Dagmar","Elisabeth"];



let firstNamesM = ["Peter","Hans","Wolfgang","Klaus","Manfred","Jürgen","Michael","Bernd","Werner","Günter","Uwe","Dieter","Carl","Helmut","Rainer","Gerhard","Horst","Harald","Joachim","Rolf","Holger","Heinz","Reinhardt","Gerd","Norbert","Thomas","Ulrich","Herbert","Detlev","Josef","Walter","Wilfried","Alexander","Lothar","Rüdiger"];


let citys = ['Berlin','Hamburg','München','Köln','Frankfurt','am Main','Stuttgart','Düsseldorf','Leipzig','Dortmund','Essen','Bremen','Dresden','Hannover','Nürnberg','Duisburg','Bochum','Wuppertal','Bielefeld','Bonn','Münster','Karlsruhe','Mannheim','Augsburg','Wiesbaden','Mönchengladbach','Gelsenkirchen','Braunschweig','Kiel','Aachen','Chemnitz','Halle ','Magdeburg','Freiburg im Breisgau','Krefeld','Lübeck','Mainz','Erfurt','Oberhausen','Rostock','Kassel','Hagen','Saarbrücken','Hamm','Potsdam','Ludwigshafen am Rhein','Mülheim an der Ruhr','Oldenburg (Oldb)','Osnabrück','Leverkusen','Heidelberg','Solingen','Herne','Neuss','Regensburg','Paderborn','Ingolstadt','Offenbach','Würzburg','Fürth','Ulm','Heilbronn','Pforzheim','Wolfsburg','Göttingen','Bottrop','Reutlingen','Koblenz','Bremerhaven','Recklinghausen','Bergisch Gladbach','Erlangen','Jena','Remscheid','Trier','Salzgitter','Moers','Siegen','Hildesheim','Cottbus','Gütersloh'];



let lastNames = ["Müller","Schmidt","Schneider","Fischer","Weber","Meyer","Wagner","Becker","Schulz","Hoffmann","Schäfer","Koch","Bauer","Richter","Klein","Wolf","Schröder (Schneider)","Neumann","Schwarz","Zimmermann","Braun","Krüger","Hofmann","Hartmann","Lange","Schmitt","Werner","Schmitz","Krause","Meier","Lehmann","Schmid","Schulze","Maier","Köhler","Herrmann","König","Walter","Mayer","Huber","Kaiser","Fuchs","Peters","Lang","Scholz","Möller","Weiß","Jung","Hahn","Schubert","Vogel","Friedrich","Keller","Günther","Frank","Berger","Winkler","Roth","Beck","Lorenz","Baumann","Franke","Albrecht","Schuster","Simon","Ludwig","Böhm","Winter","Kraus","Martin","Schumacher","Krämer","Vogt","Stein","Jäger","Otto","Sommer","Groß","Seidel","Heinrich","Brandt","Haas","Schreiber","Graf","Schulte","Dietrich","Ziegler","Kuhn","Kühn","Pohl","Engel","Horn","Busch","Bergmann","Thomas","Voigt","Sauer","Arnold","Wolff","Pfeiffer"]